### ISSUE TITLE
`nnx.jit` doesn't work with Jax 0.8.2

### ISSUE THREAD

**Issue by julian-q** [google/flax#5148]
After upgrading to `jax` 0.8.2, `flax.nnx.jit` seems to be broken:

```python
>>> import jax
>>> jax.__version__
'0.8.2'
>>> import flax
>>> flax.__version__
'0.12.1'
>>> from flax import nnx
>>> nnx.jit(lambda x: x * 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julian/code/diffseq/.venv/lib/python3.11/site-packages/flax/nnx/transforms/compilation.py", line 352, in jit
    return JitWrapped(
           ^^^^^^^^^^^
  File "/Users/julian/code/diffseq/.venv/lib/python3.11/site-packages/flax/nnx/transforms/compilation.py", line 423, in __init__
    self.jitted_fn = jax.jit(
                     ^^^^^^^^
  File "/Users/julian/code/diffseq/.venv/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 195, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: jit() got an unexpected keyword argument 'abstracted_axes'
```

I get this error on both GCP TPU VMs and on MacOS

If downgrade to `jax==0.8.1`, it works again

Sorry this issue maybe should have been in the flax repo

**Comment by vfdev-5** [comment]
Thanks for reporting @julian-q ! Seems like there is a bug to fix on flax side.

**Comment by IvyZX** [comment]
It's already fixed on https://github.com/google/flax/pull/5132, we just need to make a new release. Should be out soon.

**Comment by vfdev-5** [comment]
So, this issue is solved but we have to note the following compatibility grid:
jax | flax
--- | ---
<= 0.8.2 | 0.12.2
< 0.8.2 | < 0.12.2

**Comment by julian-q** [comment]
thanks:)
