### ISSUE TITLE
After update from 0.2.0: AttributeError: module 'jax.core' has no attribute 'eval_context'

### ISSUE THREAD

**Issue by mr128254** [google/flax#627]
After updating from flax 0.2.0 to flax 0.2.2 I get the above error message. Downgrading to 0.2.0 solves this, so the error source is located. I'm working with the now deprecated flax.nn package if backward-compatibility might be the reason for this issue.
The Issue is encountered in a custom RNN, when using the init_by_shape function in conjunction with jax.lax.scan.

**Comment by avital** [comment]
Hi @mr128254 -- we are about to officially deprecate `flax.nn` but if you have a minimal repro we can perhaps take a look. (Also have you upgraded your version of JAX in parallel to upgrading the Flax version?)

**Comment by jheek** [comment]
I am pretty sure this has something to do with the Jax version. We should raise the minimal version in `setup.py`
