### PR TITLE
Raise minimal version to 0.1.77

### LINKED ISSUE #627: After update from 0.2.0: AttributeError: module 'jax.core' has no attribute 'eval_context'
After updating from flax 0.2.0 to flax 0.2.2 I get the above error message. Downgrading to 0.2.0 solves this, so the error source is located. I'm working with the now deprecated flax.nn package if backward-compatibility might be the reason for this issue.
The Issue is encountered in a custom RNN, when using the init_by_shape function in conjunction with jax.lax.scan.

### PR DESCRIPTION
**Pull request by jheek**
Previous version constraint fails due to missing omnistaging api's.

Closes #627

### CODE REVIEW

**Comment by avital** [comment]
Thanks @jheek  for the quick fix!
