### ISSUE TITLE
`AttributeError: module 'jax.experimental.pjit' has no attribute 'PartitionSpec'`

### ISSUE THREAD

**Issue by superMDguy** [google/flax#3152]
New to Flax/Jax, but I got this error when trying to run some code:

```python
>>> from flax.linen import partitioning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.10/site-packages/flax/linen/partitioning.py", line 160, in <module>
    ) -> pjit.PartitionSpec:
AttributeError: module 'jax.experimental.pjit' has no attribute 'PartitionSpec'
```

Looks like `pjit` is [deprecated](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-11-may-31-2023)? This code works with `jax==0.4.10`, but fails with `0.4.11`

### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 13.2.1
- Flax, jax, jaxlib versions (obtain with `pip show flax jax jaxlib`: Flax 0.6.1; Jax 0.4.11; Jaxlib 0.4.11
- Python version: 3.10
- GPU/TPU model and memory: M1 Metal
- CUDA version (if applicable): N/A

**Comment by IvyZX** [comment]
Hi, you seems to be using a pretty old version of Flax. You may want to upgrade it with `pip install -U flax`.

**Comment by superMDguy** [comment]
I missed that somehow, thank you!
