### ISSUE TITLE
`nnx.cached_partial` errors on jax `Array`s not wrapped in `nnx.Variable`

### ISSUE THREAD

**Issue by am001122** [google/flax#5109]
The Pytree docs say:
> Arrays, Variables, ArrayRefs, and nnx.Pytrees are data.

which seems to imply that assigning raw `Array`s as attributes of `nnx.Pytree`s is supported. For most nnx operations it seems to work fine, but `nnx.cached_partial` fails unless all `Array`s are wrapped in variables:
```python
from flax import nnx
import jax.numpy as jnp


class Mod(nnx.Module):
    def __init__(self):
        self.a = jnp.arange(3)

    def __call__(self, x):
        return self.a * x


m = Mod()
print(m(jnp.ones(3)))

m_jit = nnx.jit(m)
print(m_jit(2 * jnp.ones(3)))


@nnx.jit
def f(mod: Mod, x):
    return mod(x) + 1


print(f(m, 3 * jnp.ones(3)))

f_partial = nnx.cached_partial(f, m)
print(f_partial(4 * jnp.ones(3)))
```
outputs
```
[0. 1. 2.]
[0. 2. 4.]
[1. 4. 7.]
...
File python3.13/site-packages/flax/nnx/graph.py:1796, in SplitContext.flatten(self, node, with_paths, *filters)
   1793   else:
   1794     paths = None
   1795     leaves = [
-> 1796       variable.get_raw_value() for variable in node_static_cache.variables
   1797     ]
   1798 else:
   1799   graphdef, flat_state = flatten(
   1800     node,
   1801     ref_index=self.ref_index,
   1802     ref_outer_index=ref_outer_index,
   1803     with_paths=with_paths,
   1804   )

AttributeError: 'jaxlib._jax.ArrayImpl' object has no attribute 'get_raw_value'
```
If I wrap it in an `nnx.Variable` everything works fine:
```
class Mod(nnx.Module):
    def __init__(self):
        self.a = nnx.Variable(jnp.arange(3))
# ...
```
gives
```
[0. 1. 2.]
[0. 2. 4.]
[1. 4. 7.]
[1. 5. 9.]
```

Is this expected behavior, and is it bad practice/unsupported to have any data in the Pytree that is not wrapped in nnx.Variable? (In the real world, I ran into this issue with a `@flax.struct.dataclass` that had data `Array` fields. I registered the whole dataclass with `nnx.register_data_type` and had assigned it as an attribute to some `nnx.Module`s, getting the same error.)

**Comment by tanvibhayani** [comment]
Maybe this update helps.
[195bb8885a6c.zip](https://github.com/user-attachments/files/23697772/195bb8885a6c.zip)

**Comment by vfdev-5** [comment]
@am001122 thanks for the report. I think it is not yet implemented: https://github.com/google/flax/blob/697f4e5cda4b110decf862a6f8ab71a0345d0412/flax/nnx/graph.py#L1621

**Comment by am001122** [comment]
@vfdev-5 aha, thanks for finding this! For the moment I've resolved this by eliminating any plain Array attributes, but it would certainly be nice for `cached_partial` to support this in order to avoid the explicit functional training loop approach from [the docs](https://flax.readthedocs.io/en/stable/guides/performance.html#functional-training-loop).

**Comment by vfdev-5** [comment]
I discussed this question with the team and unfortunately, right now `nnx.cached_partial` is expected that the function is working with `nnx.Variables` only. We need to update the docs about that.
It can be tricky to support pure arrays in the function.

**Comment by am001122** [comment]
No worries, thanks for the quick responses!  Just to clarify:  in general are pure Array attributes discouraged or bad practice in NNX?  I found the docs unclear on this point.

**Comment by vfdev-5** [comment]
No, pure arrays should be fine in general. Just in `nnx.cached_partial` it can be tricky to propagate the updates to arrays.

**Comment by mohsinm-dev** [comment]
@vfdev-5 I'm not sure if this will be good, but I’m thinking what if we make cached_partial tolerant to plain JAX arrays but treat them as read‑only: only nnx.Variables get propagated, and arrays are passed through without updates. We can document this clearly (and optionally warn), so users know that if an attribute needs to change across cached calls, it should be an nnx.Variable; otherwise, a raw array is fine.

**Comment by vfdev-5** [comment]
This makes sense. I think there is also a wider context to be taken into account, `nnx` takes the direction of pure jax transforms support such that users do not need to use `nnx.jit/vmap/grad` etc. Ideally, we would like to have something similar to `nnx.cached_partial` working with `jax.jit` and @chapman20j will be looking into that.

**Comment by AssortedFantasy** [comment]
Just gonna throw in here that I also have this issue and its not just jax arrays but numpy arrays too.

**Comment by discobot** [comment]
Dug into this: the failure isn't only the get_raw_value() call in the flatten fast path —
StaticCache.variables stores raw flatten() leaves, so the unflatten cache-update loop would
also crash on the output path for any raw array. Implemented the read-only design proposed
above (raw arrays pass through unchanged, only nnx.Variables receive updates, documented in
the cached_partial docstring) in #5501.
